import Link from 'next/link';
import { getAdminUsers, type AdminSearch } from '@/lib/admin-users';
import UserActions from '@/components/admin/UserActions';

const date = (value: Date | null) => value ? new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium', timeZone: 'America/Lima' }).format(value) : 'Sin registro';
export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<AdminSearch> }) {
  const data = await getAdminUsers(await searchParams);
  const pageLink = (page: number) => `/admin?${new URLSearchParams({ q: data.q, status: data.status, role: data.role, page: String(page) })}`;
  return <main className="ad-content"><div className="ad-page-heading"><div><span className="ad-kicker">CONTROL DE ACCESO</span><h1>Usuarios</h1><p>Consulta las cuentas registradas y gestiona su acceso a Fynit.</p></div><Link className="ad-button secondary" href="/admin/actividad">Ver actividad <span>↗</span></Link></div>
    <div className="ad-stats"><div><span>Total de usuarios</span><strong>{data.stats.total}</strong><small>{data.stats.administrators} administradores</small></div><div><span>Cuentas activas</span><strong>{data.stats.active}</strong><small>Con acceso a la plataforma</small></div><div><span>Cuentas desactivadas</span><strong>{data.stats.inactive}</strong><small>Acceso bloqueado</small></div><div><span>Nuevos registros</span><strong>{data.stats.newUsers}</strong><small>Últimos 7 días</small></div></div>
    <section className="ad-panel"><div className="ad-panel-title"><h2>Directorio de usuarios</h2><span>{data.filtered} resultados</span></div>
      <form className="ad-filters" method="get" action="/admin"><label className="ad-search"><span className="sr-only">Buscar usuarios</span><input name="q" placeholder="Buscar por nombre o correo" defaultValue={data.q} maxLength={120} /></label><label><span className="sr-only">Estado</span><select name="status" defaultValue={data.status}><option value="all">Todos los estados</option><option value="active">Activos</option><option value="inactive">Desactivados</option></select></label><label><span className="sr-only">Rol</span><select name="role" defaultValue={data.role}><option value="all">Todos los roles</option><option value="USER">Investigadores</option><option value="ADMIN">Administradores</option></select></label><button className="ad-button">Buscar</button>{(data.q || data.status !== 'all' || data.role !== 'all') && <Link className="ad-text-button" href="/admin">Limpiar</Link>}</form>
      <div className="ad-table-scroll"><table className="ad-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Registro</th><th>Último acceso</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{data.users.map(user => <tr key={user.id}><td><div className="ad-user"><span className="ad-avatar">{user.name.slice(0, 2).toUpperCase()}</span><div><strong>{user.name}{user.id === data.admin.id && <small className="ad-you">Tú</small>}</strong><span>{user.email}</span></div></div></td><td>{user.role === 'ADMIN' ? 'Administrador' : 'Investigador'}</td><td><span className={`ad-status ${user.isActive ? 'active' : 'inactive'}`}>{user.isActive ? 'Activo' : 'Desactivado'}</span></td><td>{date(user.createdAt)}</td><td>{date(user.lastLoginAt)}</td><td>{user.role === 'ADMIN' ? <span className="ad-protected">Cuenta protegida</span> : <UserActions user={{ ...user, updatedAt: user.updatedAt.toISOString() }} />}</td></tr>)}</tbody></table></div>
      {!data.users.length && <div className="ad-empty"><h3>No se encontraron usuarios</h3><p>Prueba con otro nombre, correo o combinación de filtros.</p><Link href="/admin">Restablecer filtros</Link></div>}
      <div className="ad-pagination"><span>{data.filtered ? (data.page - 1) * 20 + 1 : 0}–{Math.min(data.page * 20, data.filtered)} de {data.filtered} usuarios</span><div>{data.page > 1 && <Link href={pageLink(data.page - 1)}>← Anterior</Link>}<span>Página {data.page} de {data.pages}</span>{data.page < data.pages && <Link href={pageLink(data.page + 1)}>Siguiente →</Link>}</div></div>
    </section><p className="ad-footnote">Desactivar una cuenta conserva sus datos y bloquea su acceso. Los cambios se registran en el historial de administración.</p>
  </main>;
}
